import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/meusComponetes/footer";
import { Navbar } from "@/components/meusComponetes/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar />
      <body>
        {children}
      </body>
      < Footer/>
    </html>
  );
}
