const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const randomUUID = () => crypto.randomUUID();

// Data
const users = [
  { name: "Ana Silva", bio: "Frontend Developer apaixonada por React.", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330" },
  { name: "João Santos", bio: "Fullstack Dev e entusiasta de Rust.", avatar: "https://images.unsplash.com/photo-1599566150163-29194dcaad36" },
  { name: "Maria Costa", bio: "Designer UI/UX e ilustradora.", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80" },
  { name: "Pedro Oliveira", bio: "Engenheiro de Software focado em Backend.", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d" },
  { name: "Sofia Martins", bio: "Estudante de Ciência da Computação.", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb" },
  { name: "Lucas Ferreira", bio: "DevOps e Cloud Architect.", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e" },
  { name: "Beatriz Rodrigues", bio: "Product Manager em Tech.", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2" },
  { name: "Tiago Pereira", bio: "Mobile Developer (Flutter & Swift).", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d" },
  { name: "Inês Gomes", bio: "Data Scientist e AI Researcher.", avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9" },
  { name: "Ricardo Almeida", bio: "CTO de uma startup de Fintech.", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e" },
  { name: "Catarina Carvalho", bio: "Tech Writer e Blogger.", avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04" },
  { name: "Miguel Sousa", bio: "Game Developer Indie.", avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65ddaf" },
  { name: "Diana Lopes", bio: "QA Engineer e Automation Expert.", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956" },
  { name: "André Mendes", bio: "SysAdmin e Linux Guru.", avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61" },
  { name: "Patrícia Nunes", bio: "Marketing Digital para Tech.", avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce" },
];

const groupTopics = [
  { name: "Programadores", desc: "Comunidade para discutir código, linguagens e carreira.", image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4" },
  { name: "Frontend & UI", desc: "Tudo sobre CSS, React, Vue e Design Systems.", image: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2" },
  { name: "Inteligência Artificial", desc: "Discussions sobre LLMs, ML e o futuro da AI.", image: "https://images.unsplash.com/photo-1677442136019-21780ecad995" },
  { name: "Escrita Criativa", desc: "Partilha de textos, contos e dicas de escrita.", image: "https://images.unsplash.com/photo-1455390582262-044cdead277a" },
  { name: "Tecnologia & Startups", desc: "Empreendedorismo, inovação e tech news.", image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c" },
];

const articles = [
  { title: "Introdução ao Supabase", summary: "Como começar com o backend as a service mais popular.", cover: "https://images.unsplash.com/photo-1629904853716-6c29f6024d84" },
  { title: "React Server Components", summary: "Entendendo a nova arquitetura do React e Next.js.", cover: "https://images.unsplash.com/photo-1633356122544-f134324a6cee" },
  { title: "O Futuro da AI Generativa", summary: "O que esperar dos próximos modelos de linguagem.", cover: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485" },
  { title: "Dicas de UI Design", summary: "Melhore a interface das suas aplicações com estas dicas.", cover: "https://images.unsplash.com/photo-1586717791821-3f44a5638d48" },
  { title: "Clean Code em 2024", summary: "Práticas modernas de código limpo e manutenível.", cover: "https://images.unsplash.com/photo-1542831371-29b0f74f9713" },
  { title: "Acessibilidade na Web", summary: "Como tornar a web inclusiva para todos.", cover: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6" },
];

// Generate IDs
const userIds = users.map(u => ({ ...u, id: randomUUID(), email: `${u.name.toLowerCase().replace(/ /g, '.')}@example.com` }));
const articleIds = articles.map(a => ({ ...a, id: randomUUID() }));
const groupIds = groupTopics.map(g => ({ ...g, id: randomUUID(), created_by: userIds[0].id }));

// Helper to escape SQL strings
const esc = (str) => str ? `'${str.replace(/'/g, "''")}'` : 'NULL';

let sql = `-- Seed Data generated by script\n\n`;

// 1. Users
sql += `-- Users (Public Profile)\n`;
userIds.forEach(u => {
  // Assuming table 'users' with 'user_id' as PK
  sql += `INSERT INTO users (user_id, name, email, bio, avatar_url) VALUES ('${u.id}', ${esc(u.name)}, ${esc(u.email)}, ${esc(u.bio)}, ${esc(u.avatar)}) ON CONFLICT (user_id) DO NOTHING;\n`;
});
sql += `\n`;

// 2. Articles
sql += `-- Articles\n`;
articleIds.forEach((a, idx) => {
  // Assign random author from users
  const authorId = userIds[idx % userIds.length].id;
  // Dummy content
  const content = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`;
  
  sql += `INSERT INTO articles (article_id, title, summary, content, cover_url, author_id) VALUES ('${a.id}', ${esc(a.title)}, ${esc(a.summary)}, ${esc(content)}, ${esc(a.cover)}, '${authorId}') ON CONFLICT (article_id) DO NOTHING;\n`;
});
sql += `\n`;

// 3. Groups
sql += `-- Groups\n`;
groupIds.forEach(g => {
  sql += `INSERT INTO groups (id, name, description, image_url, created_by) VALUES ('${g.id}', ${esc(g.name)}, ${esc(g.desc)}, ${esc(g.image)}, '${g.created_by}') ON CONFLICT (id) DO NOTHING;\n`;
});
sql += `\n`;

// 4. Members
sql += `-- Group Members\n`;
groupIds.forEach(g => {
  // Add 5-10 random members to each group
  const membersCount = 5 + Math.floor(Math.random() * 6);
  const shuffledUsers = [...userIds].sort(() => 0.5 - Math.random());
  const selectedMembers = shuffledUsers.slice(0, membersCount);
  
  // Ensure creator is added as admin
  sql += `INSERT INTO group_members (group_id, user_id, role) VALUES ('${g.id}', '${g.created_by}', 'admin') ON CONFLICT (group_id, user_id) DO NOTHING;\n`;

  selectedMembers.forEach((u) => {
    if (u.id === g.created_by) return; 
    const role = Math.random() > 0.8 ? 'admin' : 'member';
    sql += `INSERT INTO group_members (group_id, user_id, role) VALUES ('${g.id}', '${u.id}', '${role}') ON CONFLICT (group_id, user_id) DO NOTHING;\n`;
  });
});
sql += `\n`;

// 5. Posts
sql += `-- Community Posts\n`;
const postTypes = ['discussion', 'feedback', 'article_share', 'question'];
const postTemplates = [
  "Alguém já usou esta tecnologia em produção? Estou a pensar migrar o meu projeto.",
  "O que acham deste design para a nova landing page?",
  "Estou a ter dificuldades com este erro de CORS, alguém sabe resolver?",
  "Partilho aqui um artigo muito interessante sobre performance.",
  "Qual a vossa opinião sobre o estado do mercado de TI em Portugal?",
  "Preciso de feedback neste projeto que estou a desenvolver nas horas vagas.",
  "Dica rápida para quem usa React Server Actions: não se esqueçam do 'use server'.",
  "Como lidam com testes E2E? Cypress ou Playwright?",
  "Alguém vai ao evento de tecnologia em Lisboa no próximo mês?",
  "Estou à procura de recomendações de livros sobre System Design.",
];

const generatedPosts = [];

groupIds.forEach(g => {
  // 5-8 posts per group
  const postsCount = 5 + Math.floor(Math.random() * 4);
  
  for (let i = 0; i < postsCount; i++) {
    const user = userIds[Math.floor(Math.random() * userIds.length)];
    const type = postTypes[Math.floor(Math.random() * postTypes.length)];
    let content = postTemplates[Math.floor(Math.random() * postTemplates.length)];
    let articleId = null;
    
    // Logic for type and content
    if (type === 'article_share') {
       const article = articleIds[Math.floor(Math.random() * articleIds.length)];
       articleId = article.id;
       content = `Acabei de ler este artigo "${article.title}" e achei fantástico! Recomendo a leitura.`;
    } else if (type === 'feedback') {
       content = "Estou a trabalhar nesta feature e gostava de saber a vossa opinião. O que acham?";
    } else if (type === 'question') {
       content = "Tenho uma dúvida sobre este tópico. Alguém consegue ajudar?";
    }
    
    // Sometimes link article even if not article_share (as per user request "Alguns posts ligados a artigos")
    if (!articleId && Math.random() > 0.8) {
       const article = articleIds[Math.floor(Math.random() * articleIds.length)];
       articleId = article.id;
       content += ` (Relacionado com este artigo)`;
    }

    const postId = randomUUID();
    generatedPosts.push({ id: postId, group_id: g.id, user_id: user.id });
    
    sql += `INSERT INTO community_posts (id, group_id, user_id, content, type, article_id) VALUES ('${postId}', '${g.id}', '${user.id}', ${esc(content)}, '${type}', ${articleId ? `'${articleId}'` : 'NULL'}) ON CONFLICT (id) DO NOTHING;\n`;
  }
});
sql += `\n`;

// 6. Comments
sql += `-- Comments\n`;
const commentTemplates = [
  "Muito bom! Obrigado pela partilha.",
  "Concordo plenamente com o que disseste.",
  "Interessante ponto de vista, não tinha pensado nisso.",
  "Podes explicar melhor a parte da implementação?",
  "Isso resolveu o meu problema, obrigado!",
  "Discordo em parte, acho que depende do contexto.",
  "Top! 🚀",
  "Vou testar e depois digo algo.",
  "Excelente artigo!",
  "Também tive esse problema na semana passada.",
];

generatedPosts.forEach(post => {
  // 1-5 comments per post
  const commentsCount = 1 + Math.floor(Math.random() * 5);
  
  for (let i = 0; i < commentsCount; i++) {
    const user = userIds[Math.floor(Math.random() * userIds.length)];
    const content = commentTemplates[Math.floor(Math.random() * commentTemplates.length)];
    
    sql += `INSERT INTO community_comments (post_id, user_id, content) VALUES ('${post.id}', '${user.id}', ${esc(content)});\n`;
  }
});
sql += `\n`;

// 7. Likes
sql += `-- Likes\n`;
generatedPosts.forEach(post => {
  // Random likes for each post (0-10)
  const likesCount = Math.floor(Math.random() * 10);
  const shuffledUsers = [...userIds].sort(() => 0.5 - Math.random());
  const likers = shuffledUsers.slice(0, likesCount);
  
  likers.forEach(user => {
    sql += `INSERT INTO community_likes (user_id, post_id) VALUES ('${user.id}', '${post.id}') ON CONFLICT (user_id, post_id) DO NOTHING;\n`;
  });
});


fs.writeFileSync(path.join(process.cwd(), 'supabase/seed.sql'), sql);
console.log('Seed file generated at supabase/seed.sql');
